aumentos/urls.py
from django.urls import path
from aumentos.views import habilitar_edicion_movimiento
from aumentos.views import eliminar_proyecto
from aumentos.views import finalizar_proyecto
from aumentos.views import editar_proyecto
from aumentos.views import crear_proyecto
from aumentos.views import eliminar_movimiento
from aumentos.views import get_aumentos_tabla
from aumentos.views import guardar_aumentocargo
from aumentos.views import guardar_aumento
from aumentos.views import editar_movimiento
from aumentos.views import crear_movimiento
from aumentos.views import modal_test
# Agrupamientos
from aumentos.views import eliminar_agrupamiento
from aumentos.views import modificar_agrupamiento
from aumentos.views import modificar_agrupamiento_save
from aumentos.views import crear_agrupamiento
from aumentos.views import template_alta_agrupamiento
from aumentos.views import actualizar_orden
from aumentos.views import valor_cargo_actual
from aumentos.views import guardar_aumento_modulo
from aumentos.views import get_cargos_modulo
from aumentos.views import cargo_baja

# Class based views
from aumentos.views import ProyectoListView
from aumentos.views import ProyectoDetailView
from aumentos.views import ProyectoCreateView
from aumentos.views import ProyectoUpdateView
from aumentos.views import ProyectoDeleteView
from aumentos.views import AumentoCargoListView
from aumentos.views import AumentoCreateView
from aumentos.views import EliminarAumento
from aumentos.views import MovimientoDetailView
from aumentos.views import MovimientoCreateView

urlpatterns = [
    # Proyecto
    path('proyecto', ProyectoListView.as_view(), name='proyecto-list'),
    path('proyecto/create', ProyectoCreateView.as_view(), name='proyecto-create'),
    path('proyecto/<int:pk>', ProyectoDetailView.as_view(), name='proyecto-detail'),
    path('proyecto/<int:pk>/update', ProyectoUpdateView.as_view(), name='proyecto-update'),
    path('proyecto/<int:pk>/delete', ProyectoDeleteView.as_view(), name='proyecto-delete'),


    path('crear_proyecto/', crear_proyecto, name='crear_proyecto'),
    path('eliminar_proyecto/', eliminar_proyecto, name='eliminar_proyecto'),
    path('editar_proyecto/', editar_proyecto, name='editar_proyecto'),
    path('finalizar_proyecto/', finalizar_proyecto, name='finalizar_proyecto'),

    # Movimiento
    path('movimiento/create', MovimientoCreateView.as_view(), name='movimiento-create'),
    path('modal/', modal_test, name='modal_test'),

    path('movimiento/<int:pk>', MovimientoDetailView.as_view(), name='movimiento-detail'),
    path('crear_movimiento/', crear_movimiento, name="crear_movimiento"),  # este tendria que volar
    path('editar_movimiento/', editar_movimiento, name='editar_movimiento'),
    path('habilitar_edicion_movimiento/', habilitar_edicion_movimiento),
    path('eliminar_movimiento/', eliminar_movimiento, name='eliminar_movimiento'),
    path('get_aumentos_tabla/', get_aumentos_tabla, name='get_aumentos_tabla'),
    path('guardar_aumentocargo/', guardar_aumentocargo, name='guardar_aumentocargo'),
    path('guardar_aumento/', guardar_aumento, name='guardar_aumento'),
    path('actualizar_orden/', actualizar_orden, name='actualizar_orden'),
    path('valor_cargo_actual/', valor_cargo_actual, name='valor_cargo_actual'),
    path('guardar_aumento_modulo/', guardar_aumento_modulo, name='guardar_aumento_modulo'),
    path('get_cargos_modulo/', get_cargos_modulo, name='get_cargos_modulo'),
    path('cargo_baja/', cargo_baja, name='cargo_baja'),

    # Agrupamiento
    path('eliminar_agrupamiento/', eliminar_agrupamiento, name='eliminar_agrupamiento'),
    path('modificar_agrupamiento/', modificar_agrupamiento, name='modificar_agrupamiento'),
    path('modificar_agrupamiento_save/', modificar_agrupamiento_save, name='modificar_agrupamiento_save'),  # FIXME
    path('crear_agrupamiento/', crear_agrupamiento, name='crear_agrupamiento'),
    path('template_alta_agrupamiento/', template_alta_agrupamiento, name='template_alta_agrupamiento'),
    path('eliminar_aumento/<int:pk>/', EliminarAumento.as_view(), name="eliminar_aumento"),
    path('cargo_codigo/<str:movimiento_id>/<str:cargo>/', AumentoCargoListView.as_view(), name="crear_cargo_codigo"),
    path('aumento_creado/', AumentoCreateView.as_view(), name="aumento_creado"),
]
 

hiscar/urls.py
from hiscar.views import local_files
from django.urls import path

urlpatterns = [
    # Proyecto
    path('local_files/', local_files, name='local_files'),
    ]

aumentos/models.py
from django.db import models
from django.db.models import Q
from django.http import HttpResponse
from django.urls.base import reverse

from main.models import CustomModel

from cuadricula.models import CuadriculaMovimiento

from hiscar.models import Cargo
from hiscar.models import Agrupamiento
from hiscar.models import Hiscar


class Proyecto(CustomModel):
    nombre       = models.CharField(max_length=60, default=None, null=True)
    descripcion  = models.CharField(max_length=120, default=None, null=True)
    fecha_limite = models.DateField(null=True)
    fecha_hiscar = models.DateField(null=True)
    is_close     = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'proyectos'
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'

    def __str__(self):
        return self.nombre + ' ' + self.descripcion

    def get_absolute_url(self):
        return reverse('proyecto-create')

    def get_movimientos(self):
        return Movimiento.objects\
            .filter(is_active=True, proyecto_id=self.id)\
            .select_related('reparticion')\
            .order_by('orden')


class Movimiento(CuadriculaMovimiento):
    """
    codigo
    periodo_dd
    periodo_ht
    nombre
    observaciones
    proyecto
    reparticion
    tipo_movimiento
    orden
    is_close
    """
    TIPOS_MOVIMIENTOS = (
        (1, 'Aumento'),
        (2, 'Alta'),
        (3, 'Baja')
    )

    tipo_movimiento = models.IntegerField(
                      choices=TIPOS_MOVIMIENTOS,
                      default=TIPOS_MOVIMIENTOS[0][0])
    orden           = models.IntegerField(blank=True, null=True)
    is_close        = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'movimientos'
        ordering = ['orden']
        verbose_name = 'Movimiento'
        verbose_name_plural = 'Movimientos'

    def __str__(self):
        return f"[{self.id}] {self.nombre}"

    def get_absolute_url(self):
        return reverse('movimiento-create')

    def get_periodo_desde(self):
        return self.periodo_dd.strftime('%Y-%m')

    def get_periodo_hasta(self):
        return self.periodo_ht.strftime('%Y-%m')

    def new_update(periodo_dd, periodo_ht, observaciones, reparticion,
                   usuario, aume_id, proyecto, orden, tipo_movimiento):
        if not aume_id or not Movimiento.objects.filter(id=aume_id).exists():
            aume = Movimiento(
                periodo_dd=periodo_dd,
                periodo_ht=periodo_ht,
                observaciones=observaciones,
                reparticion=reparticion,
                creator=usuario,
                proyecto=proyecto,
                tipo_movimiento=tipo_movimiento,
                orden=orden)

            aume.save()
            return aume.id
        else:
            Movimiento.objects\
                .filter(id=aume_id)\
                .update(
                    periodo_dd=periodo_dd,
                    periodo_ht=periodo_ht,
                    observaciones=observaciones,
                    reparticion=reparticion,
                    creator=usuario)

    def getHiscar(self):
        return Aumento.getHiscars(self.id, self.periodo_dd)

    def generar_aumentos(movimientos):
        query = Q()
        content = ''
        hiscar_aumentos = []
        movimientos_ids = [m.id for m in movimientos]
        tipos_aumentos = dict(Aumento.TIPOS_AUMENTOS)
        tipos_calculos = dict(Aumento.TIPOS_CALCULOS)

        # Obtengo los aumentos de los movimientos.
        aumentos = Aumento.objects.filter(movimiento_id__in=[m.id for m in movimientos]).order_by('orden')
        Hiscar.objects.filter(aumento_id__in=[a.id for a in aumentos]).delete()

        # Obtengo la query para filtrar reparticiones entre periodos
        periodos_reparticion_tup = [(m.periodo_dd, m.periodo_ht, m.reparticion.codigo) for m in movimientos]
        for pr in periodos_reparticion_tup:
            query.add(
                Q(
                    periodo__gte=pr[0],
                    periodo__lte=pr[1],
                    reparticion=pr[2]
                ),
                Q.OR
            )

        # Obtengo las hiscars filtrando por la query
        h = Hiscar.objects.\
            filter(query, archivo__isnull=False).\
            order_by(
                'periodo',
                'reparticion',
                'cargo').\
            all()

        #  Aplicar aumentos
        for movimiento in movimientos:
            hiscars = h.filter(periodo=movimiento.periodo_dd)
            for aumento in aumentos.filter(movimiento=movimiento):
                for hisc in hiscars.filter(aumento._get_hiscars_filter()):
                    sueldo = float(getattr(hisc, tipos_calculos[aumento.tipo_calculo]))

                    if tipos_aumentos[aumento.tipo_aumento] == 'Porcentaje':
                        monto_aumento = sueldo * float(aumento.valor) / 100
                    else:
                        monto_aumento = float(aumento.valor)

                    nuevo_sueldo = sueldo + monto_aumento
                    setattr(hisc, tipos_calculos[aumento.tipo_calculo], nuevo_sueldo)

                    hisc.pk = None
                    hisc.archivo = None
                    hisc.periodo = None
                    hisc.aumento = aumento
                    hiscar_aumentos.append(hisc)

        id_for_exc = []

        for he in hiscar_aumentos:
            nh = h.filter(
                cargo=he.cargo,
                reparticion=he.reparticion,
                archivo__isnull=False
            )
            for n in nh:
                he.periodo = n.periodo
                he.save()
                id_for_exc.append(n.id)

        nuevas_hiscars = Hiscar.objects.\
            filter(query, periodo=movimiento.periodo_dd).\
            exclude(id__in=id_for_exc).\
            order_by(
                'periodo',
                'reparticion',
                'cargo').\
            all()

        print(len(nuevas_hiscars.filter(archivo__isnull=True)))

        # ULTRA FIXME
        content += "   INSTITUTO DE PREVISION SOCIAL" + " " * 82 + "HOJA NRO.      1" + '\n'
        content += """   PGM: LISTHISC   EJECUTADO EL 25/07/2021A LAS  16:19:46  HS""" + '\n'
        content += """                   ACTUALIZACION AL MAESTRO HISTORICO DE CARGOS""" + '\n'
        content += '\n'
        content += """ AAAA MM     CODIGO          BASICO         SUPL1     SUPL2        ANTIG      SUMAFIJ1       SUMAFIJ2           SUMAFIJ3""" + '\n'

        for hh in nuevas_hiscars:
            content += hh.generate_line(movimiento.periodo_dd) + '\n'

        response = HttpResponse(content, content_type='application/text charset=utf-8')
        response['Content-Disposition'] = f"attachment; filename=movimientos{'_'.join(str(movimientos_ids))}.txt"
        return response


class Aumento(models.Model):
    """Modelo de Aumento.

    Arguments:
        models {aumento} -- Los aumentos son las
        operaciones que constituyen al movimiento

    Returns:
        object -- objeto(
            movimiento,
            tipo_aumento,
            tipo_calculo,
            cargo,
            agrupamiento,
            regla,
            valor,
            orden,
            has_modulo)
    """

    TIPOS_CALCULOS = (
        (1, 'basico'),
        (2, 'suplemento1'),
        (3, 'suplemento2'),
        (4, 'sumafija1'),
        (5, 'sumafija2'),
        (6, 'sumafija3'),
    )

    TIPOS_AUMENTOS = (
        (1, 'Porcentaje'),
        (2, 'Suma Fija'),
    )

    movimiento   = models.ForeignKey(
                   Movimiento,
                   on_delete=models.CASCADE,
                   blank=True,
                   null=True)
    tipo_aumento = models.IntegerField(
                   choices=TIPOS_AUMENTOS,
                   default=TIPOS_AUMENTOS[0][0])
    tipo_calculo = models.IntegerField(
                   choices=TIPOS_CALCULOS,
                   default=TIPOS_CALCULOS[0][0])
    cargo        = models.ForeignKey(
                   Cargo,
                   on_delete=models.CASCADE,
                   blank=True,
                   null=True)
    agrupamiento = models.ForeignKey(
                   Agrupamiento,
                   on_delete=models.CASCADE,
                   blank=True,
                   null=True)
    regla        = models.CharField(
                   max_length=256,
                   default=None,
                   blank=True,
                   null=True)
    valor        = models.DecimalField(
                   max_digits=18,
                   decimal_places=2,
                   blank=True,
                   null=True)
    orden        = models.IntegerField(
                   blank=True,
                   null=True)
    has_modulo   = models.BooleanField(
                   default=False)

    class Meta:
        db_table = 'aumentos'
        ordering = ['orden']

    def __str__(self):
        if self.TIPOS_CALCULOS[self.tipo_calculo] == 'Porcentaje':
            return '%{}->{}'.format(self.valor, self.TIPOS_CALCULOS[self.tipo_calculo])
        else:
            return '+{}->{}'.format(self.valor, self.TIPOS_CALCULOS[self.tipo_calculo])

    def modo_aumento(self):
        if self.cargo:
            return 'cargo'
        elif self.agrupamiento:
            return 'agrupamiento'
        elif self.regla:
            return 'regla'
        elif self.nuevo_cargo:
            return 'nuevo_cargo'

    def _get_hiscars_filter(self):
        if self.cargo:
            q = Q(cargo=self.cargo.codigo[4:])
        elif self.agrupamiento:
            q = Q()
            for cargo in self.agrupamiento.cargo.all():
                q.add(Q(cargo=cargo.codigo[4:]), Q.OR)
        elif self.regla:
            q = Q(cargo__startswith=self.regla[4:].replace('%', ''))  # FIXME sacar reparticion de regla
        return q

    def add_orden(self):
        try:

aumentos/forms.py
from django import forms
from .models import Movimiento


class GenerateAumentos(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)


class MovimientoMonthForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        widgets = {
            'periodo_dd': forms.TextInput(attrs={
                'type': 'month'
            }),
            'periodo_ht': forms.TextInput(attrs={
                'type': 'month',
                'value': '%Y-%m-%d'
            })
        }
        fields = '__all__'

aumentos/templates/proyecto/create.html
{% extends 'marco.html' %}

{% block title %}
<title>Proyecto</title>
{% endblock %}

{% block css_mas %}
{% endblock %}

{% block marco %}
<!-- template: detalle_proyecto.html -->

<section class="content-header">
    <h1>
        Proyecto
        <small>Create</small>
    </h1>
</section>

<section class="content">
    {% include "blocks/messages.html" %}
    {% include "blocks/errors.html" %}
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Crear Proyecto</h3>
            <div class="pull-right box-tools">
                <a href="{% url 'proyecto-list' %}" class="btn btn-sm btn-primary">Ver todas</a>
            </div>
        </div>
        <div class="box-body">
            {% include "proyecto/create_inner.html" %}
        </div>
        <a href="{% url 'proyecto-list' %}" class="btn btn-danger">Cancelar</a>
    </div>
</section>
{% endblock %}

{% block js_mas %}
{% endblock %}

aumentos/templates/proyecto/create_inner.html
{% load widget_tweaks %}

{% if perms.aumentos.add_proyecto %}
        <form method="POST" action={% url 'proyecto-create' %}>
            {% csrf_token %}
            <input type="hidden" name="creator" id="id_creator" value="{{ user.id }}">
            {% for field in form %}
                {% if field.label != "Creator" %}
                    <div class="form-group {% if field.errors %} has-error {% endif %}" >
                        <label class="form-control-label" for="{{ field.id_for_label }}">
                            {{ field.label }}
                        </label>
                        {% render_field field|add_class:"form-control" type=field.widget_type %}
                        {% if field.errors %}
                            <span class="help-block">
                                {{ field.errors }}
                            </span>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-success pull-right">Crear</button>
        </form>
{% endif %}

aumentos/templates/proyecto/delete.html
{% extends 'marco.html' %}
{% load widget_tweaks %}

{% block title %}
<title>Proyecto</title>
{% endblock %}

{% block css_mas %}
{% endblock %}

{% block marco %}
<!-- template: detalle_proyecto.html -->
<section class="content-header">
    <h1>
        Proyecto
        <small>Delete</small>
    </h1>
</section>

<section class="content">
    {% include "blocks/messages.html" %}
    <div class="box box-warning">
        <div class="box-header with-border">
            <h3 class="box-title">Eliminar Proyecto <strong>#{{ proyecto.id }}</strong></h3>
            <div class="pull-right box-tools">
                <a href="{% url 'proyecto-detail' proyecto.id %}" class="btn btn-sm btn-info">Ver</a>
                <a href="{% url 'proyecto-list' %}" class="btn btn-sm btn-primary">Ver todas</a>
            </div>
        </div>
        <form method="POST">
            {% csrf_token%}
            <div class="box-body">
                <div class="alert alert-warning" role="alert">
                    Estas seguro que quieres eliminar la proyecto <strong>{{ proyecto.nombre }}</strong> ?
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                    <a href="{% url 'proyecto-list' %}" class="btn btn-primary pull-right">Volver</a>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block js_mas %}
{% endblock %}

aumentos/templates/proyecto/list.html
{% extends 'marco.html' %}
{% load static %}
{% load tags %}

{% block title %}
<title>Proyecto</title>
{% endblock %}

{% block css_mas %}
{% endblock %}

{% block marco %}
<!-- template: abm_proyectos.html -->

<section class="content-header">
  <h1>
    Proyecto
    <small>Create</small>
  </h1>
</section>

<section class="content">
  {% include "blocks/messages.html" %}
  {% include "blocks/errors.html" %}

  <div class="box box-danger">
    <div class="box-header">
      <h3 class="box-title">Listado de Proyectos</h3>
      {% if perms.aumentos.add_proyecto%}
        <a class="btn btn-default pull-right" id="modal-create-movimiento" action="{% url 'proyecto-create' %}">
          <i class="fa fa-fw fa-plus"></i> Nuevo Proyecto
        </a>
      {% endif %}
    </div>
    <div class="box-body ">
      <div class="row">
        <div class="col-md-12">
          <table id="tabla_abm" class="table table-bordered table-striped">
            <thead>
              <th>Nombre</th>
              <th>Fecha Hiscar</th>
              <th>Fecha Limite</th>
              <th>Cant. Mov. </th>
              <th>Estado</th>
              <th> </th>
            </thead>
            <tbody>
              {% for proyecto in proyectos %}
                <tr id="row-{{proyecto.id}}" name="{{proyecto.descripcion}}">
                  <td>
                    {{proyecto.nombre}}
                  </td>
                  <td>{{ proyecto.fecha_hiscar|date:'Y-m'}} </td>
                  <td>
                    {{proyecto.fecha_limite}}
                    <small
                      class="pull-right text-danger tiempo-restante pull-right"
                      value="{{proyecto.fecha_limite|date:'Y-m-d'}}"
                      is_active="{{proyecto.is_active}}"
                      is_close="{{proyecto.is_close}}">
                    </small>
                  </td>
                  <td>
                    <small></small>
                  </td>
                  <td>
                    <small></small>
                  </td>
                  <td>
                    {% if perms.aumentos.change_proyecto %}
                      <a
                        type="button"
                        style="margin: 3px;"
                        class="btn btn-default btn-sm pull-right"
                        href="{% url 'proyecto-update' proyecto.id %}"
                      >
                      <i class="fa fa-edit fa-align-justify"></i>
                      Editar
                      </a>
                    {% endif %}
                    {% if perms.aumentos.view_proyecto %}
                      <a
                        type="button"
                        style="margin: 3px;"
                        class="btn btn-default btn-sm pull-right"
                        href="{% url 'proyecto-detail' proyecto.id %}"
                      >
                        <i class="fa fa-fw fa-align-justify"></i>
                        Ver Detalle
                      </a>
                    {% endif %}
                    {% if not proyecto.is_close %}
                        <a
                          type="button"
                          style="margin: 3px;"
                          proy_id="{{ proyecto.id}}"
                          class="btn btn-default btn-sm finalizar-proyecto pull-right"
                        >
                          <i class="fa fa-fw fa-check-square-o"></i>
                          Finalizar
                        </a>
                        {% if perms.aumentos.delete_proyecto %}
                          <a
                            href="{% url 'proyecto-delete' proyecto.id %}"
                            style="margin: 3px;"
                            class="btn btn-default btn-sm pull-right"
                          >
                            <i class="fa fa-fw fa-remove"></i>
                            Eliminar
                          </a>
                        {% endif %}
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>
{% include "blocks/modal.html" %}
{% include "blocks/spinner.html" %}
{% endblock %}
{% block js_mas %}
<!-- functions.js -->
<script src="{% static '/js/global_functions/functions.js' %}"></script>
<!-- Siliq.js -->
<script src="{% static '/js/siliq.js' %}"></script>
<!-- Proyectos.js -->
<script src="{% static '/js/proyectos.js' %}"></script>
<!-- Countdown.js -->
<script src="{% static '/plugins/jquery.countdown-2.2.0/jquery.countdown.min.js' %}"></script>

{% csrf_token %}

{% endblock %}

aumentos/templates/proyecto/update.html
{% extends 'marco.html' %}
{% load widget_tweaks %}

{% block title %}
<title>Proyecto</title>
{% endblock %}

{% block css_mas %}
{% endblock %}

{% block marco %}
<!-- template: detalle_proyecto.html -->

<section class="content-header">
    <h1>
        Proyecto
        <small>Update</small>
    </h1>
</section>

<section class="content">
    {% include "blocks/messages.html" %}
    {% include "blocks/errors.html" %}
    <div class="box box-success">
        <form method="post">
            {% csrf_token %}
            <input type="hidden" name="modifier" value="{{ user.id }}">
            <input type="hidden" name="modified" value='{% now "d/m/Y H:i" %}' data-date-format="DD/MM/YYYY hh:mm">
            <div class="box-header with-border">
                <h3 class="box-title">Modificar Proyecto</h3>
                <div class="pull-right box-tools">
                    <a href="{% url 'proyecto-detail' proyecto.id %}" class="btn btn-sm btn-info">Ver</a>
                    <a href="{% url 'proyecto-list' %}" class="btn btn-sm btn-primary">Ver todas</a>
                </div>
            </div>
            <div class="box-body">
                {% for field in form %}
                    <div class="form-group {% if field.errors %} has-error {% endif %}">
                        {% render_field field|add_class:"form-control" type=field.widget_type %}
                        {% if field.errors %}
                            <span class="help-block">
                                {{ field.errors }}
                            </span>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="box-footer">
                <a href="{% url 'proyecto-list' %}" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-warning pull-right">Actualizar</button>
            </div>
        </form>
    </div>

</section>
{% endblock %}

{% block js_mas %}
{% endblock %}