aumentos/urls.py
from django.urls import path
from aumentos.views import habilitar_edicion_movimiento
from aumentos.views import eliminar_proyecto
from aumentos.views import finalizar_proyecto
from aumentos.views import editar_proyecto
from aumentos.views import crear_proyecto
from aumentos.views import eliminar_movimiento
from aumentos.views import get_aumentos_tabla
from aumentos.views import guardar_aumentocargo
from aumentos.views import guardar_aumento
from aumentos.views import editar_movimiento
from aumentos.views import crear_movimiento
from aumentos.views import modal_test
# Agrupamientos
from aumentos.views import eliminar_agrupamiento
from aumentos.views import modificar_agrupamiento
from aumentos.views import modificar_agrupamiento_save
from aumentos.views import crear_agrupamiento
from aumentos.views import template_alta_agrupamiento
from aumentos.views import actualizar_orden
from aumentos.views import valor_cargo_actual
from aumentos.views import guardar_aumento_modulo
from aumentos.views import get_cargos_modulo
from aumentos.views import cargo_baja

# Class based views
from aumentos.views import ProyectoListView
from aumentos.views import ProyectoDetailView
from aumentos.views import ProyectoCreateView
from aumentos.views import ProyectoUpdateView
from aumentos.views import ProyectoDeleteView
from aumentos.views import AumentoCargoListView
from aumentos.views import AumentoCreateView
from aumentos.views import EliminarAumento
from aumentos.views import MovimientoDetailView
from aumentos.views import MovimientoCreateView

urlpatterns = [
    # Proyecto
    path('proyecto', ProyectoListView.as_view(), name='proyecto-list'),
    path('proyecto/create', ProyectoCreateView.as_view(), name='proyecto-create'),
    path('proyecto/<int:pk>', ProyectoDetailView.as_view(), name='proyecto-detail'),
    path('proyecto/<int:pk>/update', ProyectoUpdateView.as_view(), name='proyecto-update'),
    path('proyecto/<int:pk>/delete', ProyectoDeleteView.as_view(), name='proyecto-delete'),


    path('crear_proyecto/', crear_proyecto, name='crear_proyecto'),
    path('eliminar_proyecto/', eliminar_proyecto, name='eliminar_proyecto'),
    path('editar_proyecto/', editar_proyecto, name='editar_proyecto'),
    path('finalizar_proyecto/', finalizar_proyecto, name='finalizar_proyecto'),

    # Movimiento
    path('movimiento/create', MovimientoCreateView.as_view(), name='movimiento-create'),
    path('modal/', modal_test, name='modal_test'),

    path('movimiento/<int:pk>', MovimientoDetailView.as_view(), name='movimiento-detail'),
    path('crear_movimiento/', crear_movimiento, name="crear_movimiento"),  # este tendria que volar
    path('editar_movimiento/', editar_movimiento, name='editar_movimiento'),
    path('habilitar_edicion_movimiento/', habilitar_edicion_movimiento),
    path('eliminar_movimiento/', eliminar_movimiento, name='eliminar_movimiento'),
    path('get_aumentos_tabla/', get_aumentos_tabla, name='get_aumentos_tabla'),
    path('guardar_aumentocargo/', guardar_aumentocargo, name='guardar_aumentocargo'),
    path('guardar_aumento/', guardar_aumento, name='guardar_aumento'),
    path('actualizar_orden/', actualizar_orden, name='actualizar_orden'),
    path('valor_cargo_actual/', valor_cargo_actual, name='valor_cargo_actual'),
    path('guardar_aumento_modulo/', guardar_aumento_modulo, name='guardar_aumento_modulo'),
    path('get_cargos_modulo/', get_cargos_modulo, name='get_cargos_modulo'),
    path('cargo_baja/', cargo_baja, name='cargo_baja'),

    # Agrupamiento
    path('eliminar_agrupamiento/', eliminar_agrupamiento, name='eliminar_agrupamiento'),
    path('modificar_agrupamiento/', modificar_agrupamiento, name='modificar_agrupamiento'),
    path('modificar_agrupamiento_save/', modificar_agrupamiento_save, name='modificar_agrupamiento_save'),  # FIXME
    path('crear_agrupamiento/', crear_agrupamiento, name='crear_agrupamiento'),
    path('template_alta_agrupamiento/', template_alta_agrupamiento, name='template_alta_agrupamiento'),
    path('eliminar_aumento/<int:pk>/', EliminarAumento.as_view(), name="eliminar_aumento"),
    path('cargo_codigo/<str:movimiento_id>/<str:cargo>/', AumentoCargoListView.as_view(), name="crear_cargo_codigo"),
    path('aumento_creado/', AumentoCreateView.as_view(), name="aumento_creado"),
]
 

hiscar/urls.py
from hiscar.views import local_files
from django.urls import path

urlpatterns = [
    # Proyecto
    path('local_files/', local_files, name='local_files'),
    ]

aumentos/models.py
from django.db import models
from django.db.models import Q
from django.http import HttpResponse
from django.urls.base import reverse

from main.models import CustomModel

from cuadricula.models import CuadriculaMovimiento

from hiscar.models import Cargo
from hiscar.models import Agrupamiento
from hiscar.models import Hiscar


class Proyecto(CustomModel):
    nombre       = models.CharField(max_length=60, default=None, null=True)
    descripcion  = models.CharField(max_length=120, default=None, null=True)
    fecha_limite = models.DateField(null=True)
    fecha_hiscar = models.DateField(null=True)
    is_close     = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'proyectos'
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'

    def __str__(self):
        return self.nombre + ' ' + self.descripcion

    def get_absolute_url(self):
        return reverse('proyecto-create')

    def get_movimientos(self):
        return Movimiento.objects\
            .filter(is_active=True, proyecto_id=self.id)\
            .select_related('reparticion')\
            .order_by('orden')


class Movimiento(CuadriculaMovimiento):
    """
    codigo
    periodo_dd
    periodo_ht
    nombre
    observaciones
    proyecto
    reparticion
    tipo_movimiento
    orden
    is_close
    """
    TIPOS_MOVIMIENTOS = (
        (1, 'Aumento'),
        (2, 'Alta'),
        (3, 'Baja')
    )

    tipo_movimiento = models.IntegerField(
                      choices=TIPOS_MOVIMIENTOS,
                      default=TIPOS_MOVIMIENTOS[0][0])
    orden           = models.IntegerField(blank=True, null=True)
    is_close        = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'movimientos'
        ordering = ['orden']
        verbose_name = 'Movimiento'
        verbose_name_plural = 'Movimientos'

    def __str__(self):
        return f"[{self.id}] {self.nombre}"

    def get_absolute_url(self):
        return reverse('movimiento-create')

    def get_periodo_desde(self):
        return self.periodo_dd.strftime('%Y-%m')

    def get_periodo_hasta(self):
        return self.periodo_ht.strftime('%Y-%m')

    def new_update(periodo_dd, periodo_ht, observaciones, reparticion,
                   usuario, aume_id, proyecto, orden, tipo_movimiento):
        if not aume_id or not Movimiento.objects.filter(id=aume_id).exists():
            aume = Movimiento(
                periodo_dd=periodo_dd,
                periodo_ht=periodo_ht,
                observaciones=observaciones,
                reparticion=reparticion,
                creator=usuario,
                proyecto=proyecto,
                tipo_movimiento=tipo_movimiento,
                orden=orden)

            aume.save()
            return aume.id
        else:
            Movimiento.objects\
                .filter(id=aume_id)\
                .update(
                    periodo_dd=periodo_dd,
                    periodo_ht=periodo_ht,
                    observaciones=observaciones,
                    reparticion=reparticion,
                    creator=usuario)

    def getHiscar(self):
        return Aumento.getHiscars(self.id, self.periodo_dd)

    def generar_aumentos(movimientos):
        query = Q()
        content = ''
        hiscar_aumentos = []
        movimientos_ids = [m.id for m in movimientos]
        tipos_aumentos = dict(Aumento.TIPOS_AUMENTOS)
        tipos_calculos = dict(Aumento.TIPOS_CALCULOS)

        # Obtengo los aumentos de los movimientos.
        aumentos = Aumento.objects.filter(movimiento_id__in=[m.id for m in movimientos]).order_by('orden')
        Hiscar.objects.filter(aumento_id__in=[a.id for a in aumentos]).delete()

        # Obtengo la query para filtrar reparticiones entre periodos
        periodos_reparticion_tup = [(m.periodo_dd, m.periodo_ht, m.reparticion.codigo) for m in movimientos]
        for pr in periodos_reparticion_tup:
            query.add(
                Q(
                    periodo__gte=pr[0],
                    periodo__lte=pr[1],
                    reparticion=pr[2]
                ),
                Q.OR
            )

        # Obtengo las hiscars filtrando por la query
        h = Hiscar.objects.\
            filter(query, archivo__isnull=False).\
            order_by(
                'periodo',
                'reparticion',
                'cargo').\
            all()

        #  Aplicar aumentos
        for movimiento in movimientos:
            hiscars = h.filter(periodo=movimiento.periodo_dd)
            for aumento in aumentos.filter(movimiento=movimiento):
                for hisc in hiscars.filter(aumento._get_hiscars_filter()):
                    sueldo = float(getattr(hisc, tipos_calculos[aumento.tipo_calculo]))

                    if tipos_aumentos[aumento.tipo_aumento] == 'Porcentaje':
                        monto_aumento = sueldo * float(aumento.valor) / 100
                    else:
                        monto_aumento = float(aumento.valor)

                    nuevo_sueldo = sueldo + monto_aumento
                    setattr(hisc, tipos_calculos[aumento.tipo_calculo], nuevo_sueldo)

                    hisc.pk = None
                    hisc.archivo = None
                    hisc.periodo = None
                    hisc.aumento = aumento
                    hiscar_aumentos.append(hisc)

        id_for_exc = []

        for he in hiscar_aumentos:
            nh = h.filter(
                cargo=he.cargo,
                reparticion=he.reparticion,
                archivo__isnull=False
            )
            for n in nh:
                he.periodo = n.periodo
                he.save()
                id_for_exc.append(n.id)

        nuevas_hiscars = Hiscar.objects.\
            filter(query, periodo=movimiento.periodo_dd).\
            exclude(id__in=id_for_exc).\
            order_by(
                'periodo',
                'reparticion',
                'cargo').\
            all()

        print(len(nuevas_hiscars.filter(archivo__isnull=True)))

        # ULTRA FIXME
        content += "   INSTITUTO DE PREVISION SOCIAL" + " " * 82 + "HOJA NRO.      1" + '\n'
        content += """   PGM: LISTHISC   EJECUTADO EL 25/07/2021A LAS  16:19:46  HS""" + '\n'
        content += """                   ACTUALIZACION AL MAESTRO HISTORICO DE CARGOS""" + '\n'
        content += '\n'
        content += """ AAAA MM     CODIGO          BASICO         SUPL1     SUPL2        ANTIG      SUMAFIJ1       SUMAFIJ2           SUMAFIJ3""" + '\n'

        for hh in nuevas_hiscars:
            content += hh.generate_line(movimiento.periodo_dd) + '\n'

        response = HttpResponse(content, content_type='application/text charset=utf-8')
        response['Content-Disposition'] = f"attachment; filename=movimientos{'_'.join(str(movimientos_ids))}.txt"
        return response


class Aumento(models.Model):
    """Modelo de Aumento.

    Arguments:
        models {aumento} -- Los aumentos son las
        operaciones que constituyen al movimiento

    Returns:
        object -- objeto(
            movimiento,
            tipo_aumento,
            tipo_calculo,
            cargo,
            agrupamiento,
            regla,
            valor,
            orden,
            has_modulo)
    """

    TIPOS_CALCULOS = (
        (1, 'basico'),
        (2, 'suplemento1'),
        (3, 'suplemento2'),
        (4, 'sumafija1'),
        (5, 'sumafija2'),
        (6, 'sumafija3'),
    )

    TIPOS_AUMENTOS = (
        (1, 'Porcentaje'),
        (2, 'Suma Fija'),
    )

    movimiento   = models.ForeignKey(
                   Movimiento,
                   on_delete=models.CASCADE,
                   blank=True,
                   null=True)
    tipo_aumento = models.IntegerField(
                   choices=TIPOS_AUMENTOS,
                   default=TIPOS_AUMENTOS[0][0])
    tipo_calculo = models.IntegerField(
                   choices=TIPOS_CALCULOS,
                   default=TIPOS_CALCULOS[0][0])
    cargo        = models.ForeignKey(
                   Cargo,
                   on_delete=models.CASCADE,
                   blank=True,
                   null=True)
    agrupamiento = models.ForeignKey(
                   Agrupamiento,
                   on_delete=models.CASCADE,
                   blank=True,
                   null=True)
    regla        = models.CharField(
                   max_length=256,
                   default=None,
                   blank=True,
                   null=True)
    valor        = models.DecimalField(
                   max_digits=18,
                   decimal_places=2,
                   blank=True,
                   null=True)
    orden        = models.IntegerField(
                   blank=True,
                   null=True)
    has_modulo   = models.BooleanField(
                   default=False)

    class Meta:
        db_table = 'aumentos'
        ordering = ['orden']

    def __str__(self):
        if self.TIPOS_CALCULOS[self.tipo_calculo] == 'Porcentaje':
            return '%{}->{}'.format(self.valor, self.TIPOS_CALCULOS[self.tipo_calculo])
        else:
            return '+{}->{}'.format(self.valor, self.TIPOS_CALCULOS[self.tipo_calculo])

    def modo_aumento(self):
        if self.cargo:
            return 'cargo'
        elif self.agrupamiento:
            return 'agrupamiento'
        elif self.regla:
            return 'regla'
        elif self.nuevo_cargo:
            return 'nuevo_cargo'

    def _get_hiscars_filter(self):
        if self.cargo:
            q = Q(cargo=self.cargo.codigo[4:])
        elif self.agrupamiento:
            q = Q()
            for cargo in self.agrupamiento.cargo.all():
                q.add(Q(cargo=cargo.codigo[4:]), Q.OR)
        elif self.regla:
            q = Q(cargo__startswith=self.regla[4:].replace('%', ''))  # FIXME sacar reparticion de regla
        return q

    def add_orden(self):
        try:

cuadricula/models.py
from django.db import models


from main.models import CustomModel
from hiscar.models import Reparticion


class CuadriculaMovimiento(CustomModel):
    codigo        = models.CharField(max_length=120)
    periodo_dd    = models.DateField(
                    auto_now=False,
                    auto_now_add=False,
                    default=None,
                    null=True,
                    db_index=True)
    periodo_ht    = models.DateField(
                    auto_now=False,
                    auto_now_add=False,
                    default=None,
                    null=True,
                    db_index=True)
    nombre        = models.CharField(max_length=120)
    observaciones = models.CharField(max_length=500, null=True, blank=True)
    proyecto      = models.ForeignKey(
                    'aumentos.Proyecto',
                    on_delete=models.DO_NOTHING,
                    blank=True, null=True,
                    default=None)
    reparticion   = models.ForeignKey(
                    Reparticion,
                    on_delete=models.CASCADE,
                    blank=True, null=True)

    class Meta:
        db_table = 'cuadriculas'
        managed = True

    def __str__(self):
        return f'{self.codigo} {self.nombre}'

    def movimiento_bash(self):
        return f"""
            HISCAR=$intermedios/HISC.{self.codigo}
            export HISCAR
            echo HISCAR=$HISCAR >> $archivoDeLog


            echo "`date` - Comienza ejecucion de: {self.nombre}{self.codigo}"
            echo "`date` - Comienza ejecucion de: {self.nombre}{self.codigo}" >> $archivoDeLog
            cobrun $src/{self.nombre}{self.codigo} << EOJ >> $archivoDeLog 2> $log/ERROR.PGM
            $FHIS
            EOJ
            Resultado=$?
            if test $Resultado -eq 254
            then echo "`date` - Fin ejecucion de: {self.nombre}{self.codigo}, error 254 (cancelado)" >> $archivoDeLog
            elif test $Resultado -eq 255
            then echo "`date` - Fin ejecucion de: {self.nombre}{self.codigo}, error 255 (error de programa)" >> $archivoDeLog
            banner 'ERROR PGM.'
            exit
            else
            echo "`date` - Fin ejecucion de: {self.nombre}{self.codigo}, finalizacion OK" >> $archivoDeLog
            fi

        """.replace('            ', '')


class Comment(CustomModel):
    text = models.TextField(blank=True, null=True, default='')
    cuadricula_movimiento = models.ForeignKey(CuadriculaMovimiento, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'comments'
        managed = True

    def __str__(self):
        if self.modifier:
            return f'Comentario de {self.modifier}'
        else:
            return f'Comentario de {self.creator}'

aumentos/forms.py
from django import forms
from .models import Movimiento


class GenerateAumentos(forms.Form):
    _selected_action = forms.CharField(widget=forms.MultipleHiddenInput)


class MovimientoMonthForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        widgets = {
            'periodo_dd': forms.TextInput(attrs={
                'type': 'month'
            }),
            'periodo_ht': forms.TextInput(attrs={
                'type': 'month',
                'value': '%Y-%m-%d'
            })
        }
        fields = '__all__'

aumentos/templates/movimiento/create_in_proyecto.html
<!-- template: movimiento/create_in_proyecto.html -->

<!-- Modal nuevo Movimiento-->

<div class="modal fade" id="modal-default" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title">Nuevo Movimiento</h4>
      </div>
      {% if perms.aumentos.add_movimiento %}
      <form action="{% url 'movimiento-create' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="proyecto_id" value="{{proyecto.id}}">
        <div class="box-body">
          <div class="form-group col-md-12">
            <label>Descripcion: </label>
            <input required type="name" name="nombre" class="form-control"  placeholder="Descripcion">
          </div>

          <div class="form-group col-md-12">
            <label>Tipo: </label>
            <select class="select2" name="tipo_movimiento" style="border-radius:0px ; width: 100%;" required>
              <option value="1">Aumento</option>
              <option value="2">Baja Cargos</option>
              <option value="3">Alta Cargos</option>
            </select>
          </div>

          <div class="form-group col-md-12">
            <label style="margin-bottom: 10px">Reparticion: </label>
            <select name="reparticion_id" class="select2" style="border-radius:0px ; width: 100% "required>
              {% for reparticion in reparticiones %}
              <option value="{{reparticion.id}}">
                {{reparticion.codigo}}&nbsp;&nbsp;{{reparticion.nombre}}
              </option>
              {% endfor %}
            </select>
          </div>
          <div class="form-group col-md-6">
            <label>Periodo Desde: </label>
            <input required type="month" class="form-control" name="periodo_dd">
          </div>
          <div class="form-group col-md-6">
            <label>Periodo Hasta: </label>
            <input required type="month" class="form-control" name="periodo_ht">
          </div>
          <div class="form-group col-md-6">
            <label>observaciones </label>
            <input class="form-control" name="observaciones">
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Crear</button>
        </div>
      </form>
      {% else %}
        <div class="modal-body">
          <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i> Error!</h4>
            No tiene permisos para crear un movimiento.
          </div>
      {% endif %}
    </div>
  </div>
</div>

<!-- template: movimiento/create_in_proyecto.html -->

aumentos/templates/movimiento/create_inner.html
<!-- template: movimiento/create_inner.html -->
{% load widget_tweaks %}

      {% if perms.aumentos.add_movimiento %}
        <form method="POST" action={% url 'movimiento-create' %}>
          {% csrf_token %}
          <input type="hidden" name="proyecto" id="id_proyecto" value="{{ proyecto_id }}">
          <input type="hidden" name="creator" id="id_creator" value="{{ user.id }}">
          {% for field in form %}
            {% if field.label != "Creator" and field.label != "Proyecto" %}
              <div class="form-group {% if field.errors %} has-error {% endif %}" >
                  <label class="form-control-label" for="{{ field.id_for_label }}">
                      {{ field.label }}
                  </label>
                  {% render_field field|add_class:"form-control" type=field.widget_type%}
                  {% if field.errors %}
                      <span class="help-block">
                          {{ field.errors }}
                      </span>
                  {% endif %}
              </div>
            {% endif %}
          {% endfor %}
          <button type="submit" class="btn btn-success pull-right">Crear</button>
        </form>
      {% else %}
        <div class="modal-body">
          <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-ban"></i> Error!</h4>
            No tiene permisos para crear un movimiento.
          </div>
        </div>
      {% endif %}

<!-- template: movimiento/create_inner.html -->

aumentos/templates/movimiento/detail.html
{% extends 'marco.html' %} {% load static %} {% load tags %} {% block title %}
<title>Movimiento</title>
{% endblock %} {% block descipcion %}
<h1>Movimiento {{ municipio }}</h1>
{% endblock %} {% block marco %}
<!-- template: movimiento/detail.html -->
<section class="content container-fluid">
    <div class="row">
        {% if perms.aumentos.change_movimiento %}
        <div id="crear_aumento" class="col-md-12">
            {% include "movimiento/update_in_movimiento.html" %}
        </div>
        {% endif %} {% if not movimiento.is_close and perms.aumentos.create_aumento%}
        <div id="elegir_cargos" class="col-md-5">
            {% include "aumento/create.html" %}
        </div>
        {% endif %}


        <div id="aumentos" class="col-md-7 formularios_aumento" hidden>
            {% if reparticion.has_modulo %} {% include "aumento/create_by_modulo.html" %} {% else %} {% include "aumento/create_valores.html" %} {% endif %}
        </div>

        <div class="col-md-12">
            {% if perms.aumentos.change_movimiento and perms.aumentos.view_aumento %} {% include "aumento/list_table.html" %} {% else %}
            <div class="callout callout-danger">
                <h4>
                    No tiene permisos para ver los aumentos.
                </h4>
                Ante cualquier duda contactar con los administradores.
            </div>
            {% endif %}
        </div>

    </div>
</section>


<div class="modal fade" id="eliminacion" role="dialog">

</div>

{% include "blocks/spinner.html" %} {% include "blocks/confirmDeleteModal.html" %} {% include "blocks/modal.html" %} {% endblock %} {% block js_mas %}
<script>
    var aumento_id = "{{aumento.id}}"
    var movimiento_id = "{{ movimiento.id }}",
        reparticion_codigo = "{{ reparticion.codigo }}",
        reparticion_id = "{{ reparticion.id }}";
</script>
<!-- DataTable Row Reorder js -->
<script src="{% static '/bower_components/datatables.net-bs/js/dataTables.rowReorder.min.js' %}"></script>
<!-- Aumentos.js -->
<script src="{% static '/js/aumentos.js' %}"></script>
<script src="{% static '/js/aumentos/eliminar_aumentos.js' %}"></script>
<script src="{% static '/js/aumentos/tabla_aumentos.js' %}"></script>

<!-- Siliq.js -->
<script src="{% static '/js/siliq.js' %}"></script>
<script src="{% static 'js/sweetalert2.all.min.js' %}"></script>



{% endblock %}

aumentos/templates/movimiento/update_in_movimiento.html
<!-- template: update_in_movimiento.html -->

<div class="box box-success box-solid" id="box-aumento-crear">
    <div class="box-header with-border">
        <h3 class="box-title" repart-id="{{ reparticion.id }}" id="repart-aume" />
        <a class="btn btn-success btn-xs" href="{% url 'proyecto-detail' proyecto.id %}">
            <i class="fa fa-fw  fa-mail-reply"></i> Atras
        </a>
        <h3 class="box-title" proy_id="{{proyecto.id}}" repart-id="{{ reparticion.id }}" id="repart-aume">
            <strong>&nbsp;&nbsp;Reparticion {{ reparticion.codigo }} - {{ reparticion.nombre }}: </strong>
            <span id="aume-desc-colapsed" />
        </h3>
        <h3 class="box-title" id="aume-desc-rango-colapsed"></h3>
        {% if not movimiento.is_close %}
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-success btn-sm" id="tool-aumento">Editar <i class="fa fa-edit"></i>
            </button>
        </div>
        {% endif %}
    </div>
    <!-- /.box-header -->
    <div class="box-body" hidden>
        <form action="/aumentos/editar_movimiento/" id="formulario_editar_movimiento" method="POST">
            {% csrf_token %}
            <input
                type="hidden"
                name="movimiento_id"
                value="{% if movimiento %}{{ movimiento.id }}{% endif %}"
            />
            <div class="item-required col-xs-8">
                <label for="aume-desc">Nombre: </label>
                <input
                    type="text"
                    name="movimiento_nombre"
                    class="form-control"
                    placeholder="Nombre del movimiento .."
                    value="{% if movimiento %}{{ movimiento.nombre }}{% endif %}"
                    required
                >
            </div>
            <div class="item-required col-xs-4">
                <div class="col-xs-6">
                        <label for="periodos-aumento-dd">Periodo desde:</label>
                        <input
                            type="month"
                            name="movimiento_periodo_dd"
                            class="form-control"
                            value="{% if movimiento %}{{ movimiento.periodo_dd|date:'Y-m' }}{% endif %}"
                            required
                        >
                </div>
                <div class="col-xs-6">
                    <label for="periodos-aumento-ht">Periodo hasta</label>
                    <input
                        type="month"
                        class="form-control"
                        name="movimiento_periodo_ht"
                        value="{% if movimiento %}{{ movimiento.periodo_ht|date:'Y-m' }}{% endif %}"
                    >
                </div>

            </div>

            <div class="col-xs-12" style="padding-top: 20px;">
                <input type="submit" class="btn btn-success btn-flat pull-right" value="Guardar"></input>
                <button type="button" class="btn btn-danger btn-flat pull-right"
                    onclick="ocultarAumentoBox();">Cancelar</button>
            </div>
        </form>
    </div>
</div>